apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .ServiceName }}
    spec:
      containers:
      - name: {{ .ServiceName }}
        image: docker.io/dstroot/{{ .ServiceName }}:{{ .Release }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 250m
            memory: 128Mi # 128 MiB
          limits:
            cpu: 500m
            memory: 256Mi
      terminationGracePeriodSeconds: 5
# Limits and requests for CPU resources are measured in cpu units. One cpu,
# in Kubernetes, is equivalent to:
#  - 1 AWS vCPU
#  - 1 GCP Core
#  - 1 Azure vCore
#  - 1 Hyperthread on a bare-metal Intel processor with Hyperthreading

# Fractional requests are allowed. The expression 0.1 is equivalent to
# the expression 100m, which can be read as “one hundred millicpu”.
# Some people say “one hundred millicores”, and this is understood to
# mean the same thing.
